services:
  - type: web
    name: aesthete-api
    runtime: docker
    region: singapore
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/categories
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_SCHEMA
        value: aesthete
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: OMISE_PUBLIC_KEY
        value: pkey_test_689gs96ehzjmf5537qy
      - key: OMISE_SECRET_KEY
        value: skey_test_689gs96uyhn5qdplvi6
